### ISSUE TITLE
Docxtemplater is not defined ( browser )

### ISSUE THREAD

**Issue by raminahmadi1986** [open-xml-templating/docxtemplater-build#1]
Hi,
I'm using the below code , but I got this error : Docxtemplater is not defined.

```
<html>
    <script src="js/docxtemplater.min.js"></script>
    <script src="js/FileSaver.min.js"></script>
    <script src="js/jszip-utils.min.js"></script>
    <!--
    Mandatory in IE 6, 7, 8 and 9.
    -->
    <!--[if IE]>
        <script type="text/javascript" src="js/jszip-utils-ie.js"></script>
    <![endif]-->
    <script>
    var loadFile=function(url,callback){
        JSZipUtils.getBinaryContent(url,callback);
    }
    loadFile("sample.pptx",function(err,content){
        if (err) { throw e};
        doc=new Docxtemplater(content);
		doc.setOptions({fileType: "pptx"});
        doc.setData( {"first_name":"Hipp",
            "last_name":"Edgar",
            "phone":"0652455478",
            "description":"New Website"
            }
        ) //set the templateVariables
        doc.render() //apply them (replace all occurences of {first_name} by Hipp, ...)
        out=doc.getZip().generate({type:"blob"}) //Output the document using Data-URI
        saveAs(out,"output.docx")
    })
    </script>
</html>
```

what's wrong here ?

**Comment by edi9999** [comment]
It should be new Docxgen(content) (for legacy reasons)

**Comment by raminahmadi1986** [comment]
Thanks , it works now , but why it doesn't change the tag names ?
I create some tags like {first_name} in my pptx file but after it creates the file all tags remain unchange

**Comment by edi9999** [comment]
Try it this way around : 

```
doc=new Docxtemplater();
doc.setOptions({fileType: "pptx"});
doc.load(content);
```

With the syntax that you use, it doesn't work (it is a bug in docxtemplater, which has been fixed in https://github.com/open-xml-templating/docxtemplater/commit/c7ee61ab1eead3b0e0eab6a66526cdf445ae0f76, but the latests released version 2.1.1 doesn't have that fix yet), 2.1.2 will have it when I release it, probably tomorrow.

**Comment by raminahmadi1986** [comment]
Great ! it works this way , I'm waiting to get the new version , thanks again :)

**Comment by edi9999** [comment]
The second problem has been solved since 2.1.2 (just released)

**Comment by cweseloh** [comment]
I'm having the same problem using the latest (3.0.0) and the sample code from the readthedocs site (http://docxtemplater.readthedocs.io/en/latest/generate.html#browser)

**Comment by edi9999** [comment]
Sorry, indeed, this has now been fixed.

Please now use : https://github.com/open-xml-templating/docxtemplater-build/blob/master/build/docxtemplater.v3.0.3.js or the minified file.

**Comment by cweseloh** [comment]
That fixed it - thanks!
